-- CREATE TABLE DEPARTMENT(ID TEXT PRIMARY KEY,NAME TEXT);
-- CREATE TABLE USER(UID TEXT PRIMARY KEY,NAME TEXT,EMAIL TEXT,ROLE TEXT,HOD_ID TEXT,ID TEXT,FOREIGN KEY(HOD_ID) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE);
-- CREATE TABLE ATTENDANCE(ID TEXT PRIMARY KEY,STATUS TEXT,DATE TEXT,UID TEXT,LINK TEXT, FOREIGN KEY(UID) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(LINK) REFERENCES MATERIAL(LINK) ON DELETE CASCADE ON UPDATE CASCADE);
-- CREATE TABLE SECTION(SID TEXT PRIMARY KEY,NAME TEXT,DID TEXT,FOREIGN KEY(DID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE);
-- CREATE TABLE SUBJECT(CODE TEXT PRIMARY KEY,NAME TEXT,SID TEXT,UID TEXT,FOREIGN KEY(UID) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY(SID) REFERENCES SECTION(SID) ON DELETE CASCADE ON UPDATE CASCADE);
-- CREATE TABLE CLASS(LINK TEXT PRIMARY KEY,TIME TEXT,CODE TEXT,FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE) ON DELETE CASCADE ON UPDATE CASCADE);
-- CREATE TABLE MATERIAL(LINK TEXT PRIMARY KEY,DATE TEXT,TYPE TEXT,DESCRIPTION TEXT,CODE TEXT, FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE) ON DELETE CASCADE ON UPDATE CASCADE);
SELECT * FROM sqlite_master WHERE type="table";
-- CREATE TABLE STUDENT(USN TEXT PRIMARY KEY,ID TEXT,FOREIGN KEY(USN) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY(ID) REFERENCES SECTION(SID));
