-- SQLite
SELECT * FROM sqlite_master WHERE type="table";
-- DROP TABLE SECTION;
-- DROP TABLE MATERIAL;
-- DROP TABLE STUDENT;
-- DROP TABLE ADMINDEPT;
-- DROP TABLE ADMINMAIN;

-- CREATE TABLE SECTION(SECID TEXT PRIMARY KEY,NAME TEXT,NO_OF_SUBJECTS INTEGER, NO_OF_STUDENTS INTEGER,ID TEXT, FOREIGN KEY(ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE);
-- CREATE TABLE MATERIAL(LINK TEXT PRIMARY KEY, DESCRIPTION TEXT,TYPE TEXT,DATE_ADDED TEXT,SUBID TEXT, FOREIGN KEY(SUBID) REFERENCES SUBJECT(ID));
-- CREATE TABLE STUDENT(EMAIL TEXT,USN TEXT PRIMARY KEY,NAME TEXT,SECID TEXT, FOREIGN KEY(SECID) REFERENCES SECTION(ID) ON UPDATE CASCADE ON DELETE CASCADE);
-- CREATE TABLE ADMINDEPT(EMAIL TEXT PRIMARY KEY, NAME TEXT,ID TEXT,FOREIGN KEY(ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY(EMAIL) REFERENCES CREDENTIALS(EMAIL));
-- CREATE TABLE ADMINMAIN(EMAIL TEXT PRIMARY KEY,NAME TEXT,FOREIGN KEY(EMAIL) REFERENCES CREDENTIALS(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE);
