-- SQLite
SELECT * FROM CREDENTIALS;

-- UPDATE CREDENTIALS SET ROLE="HOD" WHERE EMAIL="HOD.basicscience@NMAM.in";
-- UPDATE CREDENTIALS SET ROLE="ASST. PROFESSOR" WHERE EMAIL="ramesh123@gmail.com";
-- UPDATE CREDENTIALS SET ROLE="NULL" WHERE EMAIL="manjukrishna123@gmail.com";

-- UPDATE CREDENTIALS SET ROLE="ADMIN";